export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.poetry/bin"
export PATH="$HOME/.pyenv/bin:$PATH"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
