export PATH="$PATH:$HOME/.local/bin"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
export PATH="$PATH:$HOME/.poetry/bin"
export GUIX_PROFILE="$HOME/.config/guix/current"
export PATH="$PATH:/home/pavlos/.cargo/bin"
