;; This "manifest" file can be passed to 'guix package -m' to reproduce
;; the content of your profile.  This is "symbolic": it only specifies
;; package names.  To reproduce the exact same profile, you also need to
;; capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(specifications->manifest
  (list "linux-pam"
        "pam-u2f"
        "pam-mount"
        "cifs-utils"
        "gvfs"
        "samba"
        "nautilus"
        "icedove-wayland"
        "wob"
        "kodi"
        "gtk+:bin"
        "emacs-pgtk-native-comp"
        "fontmanager"
        "materia-theme"
        "gtk-layer-shell"
        "gtk+"
        "matcha-theme"
        "swaybg"
        "gsettings-desktop-schemas"
        "go"
        "make"
        "mpv"
        "cairo"
        "libxkbcommon"
        "wl-clipboard"
        "firefox-wayland"
        "xeyes"
        "geoclue"
        "slurp"
        "grim"
        "kanshi"
        "font-openmoji"
        "font-gnu-freefont"
        "fontconfig"
        "emacs-all-the-icons"
        "font-awesome"
        "recutils"
        "udiskie"
        "swappy"
        "gammastep"
        "wlogout"
        "mako"
        "wofi"
        "swaylock"
        "swayidle"
        "firefox"
        "waybar"
        "ungoogled-chromium"
        "clojure"
        "nano"
        "perl"
        "tmux"
        "flatpak"
        "unzip"
        "zsh"
        "curl"
        "icecat"
        "alacritty"
        "xterm"
        "git"
        "emacs"
        "jq"
        "lvm2"
        "sway"
        "steam"
        "nss-certs"
        "font-dejavu"
        "gs-fonts"
        "glibc-locales"))
