# Hardware configuration template for NixOS
# This file should be generated by nixos-generate-config during installation
# Template based on system inventory for Intel i5-6300U ThinkPad

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Boot configuration
  boot.initrd.availableKernelModules = [
    "xhci_pci"      # USB 3.0 controller
    "ahci"          # SATA controller
    "usb_storage"   # USB storage devices
    "sd_mod"        # SD card support
    "rtsx_pci_sdmmc" # Realtek card reader
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ]; # Intel virtualization
  boot.extraModulePackages = [ ];

  # Filesystem configuration (template - adjust based on actual installation)
  fileSystems."/" = {
    device = "/dev/sda2";
    fsType = "btrfs";
    options = [ "subvol=@" "compress=zstd" "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/sda1";
    fsType = "ext4";
  };

  # Swap configuration (using zram like current Fedora setup)
  swapDevices = [ ];
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 25; # Use 25% of RAM for compressed swap
  };

  # Network interfaces (from system inventory)
  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  # Hardware acceleration and graphics
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Power management
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  # Additional hardware-specific settings for ThinkPad
  services.thermald.enable = lib.mkDefault true;

  # Enable firmware updates for ThinkPad
  services.fwupd.enable = lib.mkDefault true;
}
